version: "3"

services:
  emtii-httpd:
    container_name: emtii.httpd
    build: ./build/httpd/
    ports:
      - 80:80
    links:
      - emtii-php

  emtii-php:
    container_name: emtii.php
    build: ./build/php-fpm/
    expose:
      - 9000
    links:
      - emtii-mysql-master

  emtii-mysql-master:
    container_name: emtii.mysql.master
    build: ./build/mysql/master
    ports:
      - '3306'
    volumes_from:
      - emtii-mysql
    env_file:
      - ./build/mysql/variables.env

  emtii-mysql-slave-1:
    container_name: emtii.mysql.slave.1
    build: ./build/mysql/slave
    ports:
      - '3306'
    depends_on:
      - mysql-master
    env_file:
      - ./build/mysql/variables.env
      - ./build/mysql/slave/variables.env

  emtii-mysql-slave-2:
    container_name: emtii.mysql.slave.2
    build: ./build/mysql/slave
    ports:
      - '3306'
    depends_on:
      - mysql-master
    env_file:
      - ./build/mysql/variables.env
      - ./build/mysql/slave/variables.env

 emtii-redis:
    container_name: emtii.redis
    build: ./build/redis
    ports:
      - "6379"

volumes:
  emtii-mysql:
    driver: local
  emtii-app:
    driver: local
