emtii-local-nginx:
  build: ./build/nginx/
  ports:
    - 80:80
  links:
    - emtii-local-php
  volumes:
    - .:/var/www/html

emtii-local-php:
  image: php:7.0-fpm-alpine
  expose:
    - 9000
  volumes:
    - .:/var/www/html