emtii-local-nginx:
  container_name: emtii.local.nginx
  build: ./build/nginx/
  ports:
    - 80:80
  links:
    - emtii-local-php
  volumes_from:
    - emtii-local-app

emtii-local-php:
  container_name: emtii.local.php
  image: php:7.0-fpm-alpine
  expose:
    - 9000
  volumes_from:
    - emtii-local-app

emtii-local-app:
  container_name: emtii.local.app
  image: busybox:musl
  volumes:
    - .:/var/www/html
  command: "true"